# Generated by Django 3.2.9 on 2022-01-13 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_auto_20220113_2021'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follower',
            old_name='follower',
            new_name='followers',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='liker',
            new_name='likers',
        ),
    ]
